name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - 'Nodejs/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          
      - name: Install dependencies
        working-directory: ./Nodejs
        run: npm ci
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./Nodejs
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'chatgpt-server'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREWEBAPP_PUBLISHPROFILE_NODEJS }}
          package: ./Nodejs