name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - 'Nodejs/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'chatgpt-server'  # Replace with your Azure app name
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREWEBAPP_PUBLISHPROFILE_NODEJS }}
          package: .